version: '3.1'

services:
  mush-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/app/src
    container_name: mush-api
    ports:
      - "5000:5000"
  postgres:
    image: postgres
    restart: always
    volumes:
      - "dbdata:/var/lib/postgresql/data:Z"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"

volumes:
  dbdata:

